#ifndef __GPON_DBA_LSTM_GPONMSG_M_H
#define __GPON_DBA_LSTM_GPONMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace gpon_dba_lstm {

class DemandReport;
class Grant;
class DataPacket;

}  


namespace gpon_dba_lstm {

class DemandReport : public ::omnetpp::cMessage
{
  protected:
    int onuId = 0;
    long demandBytes = 0;
    double simTime = 0;

  private:
    void copy(const DemandReport& other);

  protected:
    bool operator==(const DemandReport&) = delete;

  public:
    DemandReport(const char *name=nullptr, short kind=0);
    DemandReport(const DemandReport& other);
    virtual ~DemandReport();
    DemandReport& operator=(const DemandReport& other);
    virtual DemandReport *dup() const override {return new DemandReport(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getOnuId() const;
    virtual void setOnuId(int onuId);

    virtual long getDemandBytes() const;
    virtual void setDemandBytes(long demandBytes);

    virtual double getSimTime() const;
    virtual void setSimTime(double simTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DemandReport& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DemandReport& obj) {obj.parsimUnpack(b);}


class Grant : public ::omnetpp::cMessage
{
  protected:
    int onuId = 0;
    long grantBytes = 0;
    double simTime = 0;

  private:
    void copy(const Grant& other);

  protected:
    bool operator==(const Grant&) = delete;

  public:
    Grant(const char *name=nullptr, short kind=0);
    Grant(const Grant& other);
    virtual ~Grant();
    Grant& operator=(const Grant& other);
    virtual Grant *dup() const override {return new Grant(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getOnuId() const;
    virtual void setOnuId(int onuId);

    virtual long getGrantBytes() const;
    virtual void setGrantBytes(long grantBytes);

    virtual double getSimTime() const;
    virtual void setSimTime(double simTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Grant& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Grant& obj) {obj.parsimUnpack(b);}


class DataPacket : public ::omnetpp::cMessage
{
  protected:
    int onuId = 0;
    long sizeBytes = 0;
    double arrivalTime = 0;
    double departureTime = 0;

  private:
    void copy(const DataPacket& other);

  protected:
    bool operator==(const DataPacket&) = delete;

  public:
    DataPacket(const char *name=nullptr, short kind=0);
    DataPacket(const DataPacket& other);
    virtual ~DataPacket();
    DataPacket& operator=(const DataPacket& other);
    virtual DataPacket *dup() const override {return new DataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getOnuId() const;
    virtual void setOnuId(int onuId);

    virtual long getSizeBytes() const;
    virtual void setSizeBytes(long sizeBytes);

    virtual double getArrivalTime() const;
    virtual void setArrivalTime(double arrivalTime);

    virtual double getDepartureTime() const;
    virtual void setDepartureTime(double departureTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DataPacket& obj) {obj.parsimUnpack(b);}

}  


namespace omnetpp {

template<> inline gpon_dba_lstm::DemandReport *fromAnyPtr(any_ptr ptr) { return check_and_cast<gpon_dba_lstm::DemandReport*>(ptr.get<cObject>()); }
template<> inline gpon_dba_lstm::Grant *fromAnyPtr(any_ptr ptr) { return check_and_cast<gpon_dba_lstm::Grant*>(ptr.get<cObject>()); }
template<> inline gpon_dba_lstm::DataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<gpon_dba_lstm::DataPacket*>(ptr.get<cObject>()); }

}  

#endif